import { ArrowRight, Box, CalendarDays, Camera, ChevronRight, Clock3, KeyRound, LockKeyhole, PackageCheck, ParkingCircle, ReceiptText, ShieldCheck, Snowflake, Warehouse } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ImageCredit } from '../../components/public/ImageCredit'
import { QuickFinder } from '../../components/public/QuickFinder'
import { ButtonLink } from '../../components/ui/ButtonLink'
import { Container } from '../../components/ui/Container'
import { faqs, imageCredits, storageSizes } from '../../data/storage'

export function LandingPage() {
  return <>
    <section className="bg-white"><Container className="grid min-h-[650px] items-stretch px-0 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="flex items-center px-5 py-16 sm:px-8 lg:px-0 lg:pr-16"><div><p className="eyebrow">Kho tự quản · Một cơ sở tại TP.HCM</p><h1 className="mt-5 max-w-xl text-5xl leading-[1.06] font-bold tracking-[-.03em] sm:text-6xl">Thêm chỗ cho cuộc sống đang chuyển động.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate">Không gian riêng, an toàn và linh hoạt cho đồ gia đình, hồ sơ hay hàng kinh doanh. Chọn kích thước bằng những vật dụng quen thuộc, rồi gửi yêu cầu giữ chỗ khi đã sẵn sàng.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink to="/storage">Xem kho đang nhận yêu cầu <ArrowRight size={18} /></ButtonLink><ButtonLink to="/size-guide" variant="secondary">Hướng dẫn kích thước</ButtonLink></div><div className="mt-10 grid max-w-xl grid-cols-2 gap-x-6 gap-y-4 border-t border-border pt-6 text-sm text-slate"><span><ShieldCheck /> An ninh nhiều lớp</span><span><Clock3 /> Truy cập thuận tiện</span><span><Snowflake /> Kho thường & điều hòa</span><span><CalendarDays /> Thời hạn linh hoạt</span></div></div></div><figure className="relative min-h-[430px] overflow-hidden bg-slate-100 lg:min-h-full"><img src={imageCredits.hero.src} alt="Ảnh minh họa một khu lưu trữ với các thùng hàng được sắp xếp gọn gàng" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-ink/80 to-transparent px-6 pt-20 pb-6"><ImageCredit label={imageCredits.hero.label} href={imageCredits.hero.href} /><p className="mt-2 max-w-md text-xs text-white/80">Hình ảnh chỉ minh họa loại hình lưu trữ, không phải cơ sở WDP thực tế.</p></div></figure></Container></section>

    <section className="border-y border-border bg-canvas py-8"><Container><div className="mb-5 flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="eyebrow">Tìm kho nhanh</p><h2 className="mt-2 text-2xl font-semibold">Bắt đầu từ nhu cầu của bạn</h2></div><Link className="text-sm font-semibold text-navy hover:underline" to="/size-guide">Chưa biết chọn cỡ nào?</Link></div><QuickFinder /></Container></section>

    <section id="sizes" className="section-space scroll-mt-24"><Container><div className="section-heading"><div><p className="eyebrow">Bốn nhóm kích thước</p><h2>Từ vài chiếc vali đến cả một căn hộ</h2></div><p>Thông số được chuẩn hóa theo diện tích sàn, thể tích và lượng đồ ước tính để bạn dễ đối chiếu.</p></div><div className="mt-12 grid border-y border-border sm:grid-cols-2 lg:grid-cols-4">{storageSizes.map((size, index) => <article key={size.id} className={`group py-7 sm:px-6 lg:px-7 ${index > 0 ? 'sm:border-l sm:border-border' : ''}`}><div className="flex items-end justify-between"><span className="text-5xl font-bold tracking-tight text-navy">{size.floorArea}</span><span className="text-sm font-semibold text-orange">{size.boxCount}</span></div><div className="mt-5 h-1 bg-border"><div className="h-full bg-navy transition-all duration-200 group-hover:bg-orange" style={{ width: `${size.illustrationScale}%` }} /></div><h3 className="mt-6 text-xl font-semibold">{size.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate">{size.roomEquivalent}</p><Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-navy" to={`/size-guide?size=${size.id}`}>Xem sức chứa <ChevronRight size={16} /></Link></article>)}</div></Container></section>

    <section className="section-space bg-white"><Container><div className="section-heading"><div><p className="eyebrow">Điều kiện bảo quản</p><h2>Kho tiêu chuẩn hay kho điều hòa?</h2></div><p>Lựa chọn dựa trên vật dụng và thời gian lưu trữ, không chỉ dựa trên mức phí.</p></div><div className="mt-12 grid border border-border md:grid-cols-2"><article className="p-7 sm:p-10 md:border-r md:border-border"><Warehouse className="text-navy" size={30} /><h3 className="mt-5 text-2xl font-semibold">Kho tiêu chuẩn</h3><p className="mt-3 leading-7 text-slate">Không gian khô ráo, thông thoáng cho đồ gia dụng và hàng hóa thông thường.</p><dl className="comparison-list"><div><dt>Phù hợp</dt><dd>Thùng đồ, dụng cụ, nội thất bền, hàng đóng gói</dd></div><div><dt>Môi trường</dt><dd>Theo điều kiện thông thoáng của cơ sở</dd></div><div><dt>Chi phí</dt><dd>Thường thấp hơn kho điều hòa</dd></div></dl><ButtonLink to="/storage?type=standard&size=all&duration=3" variant="secondary">Xem kho tiêu chuẩn</ButtonLink></article><article className="bg-canvas p-7 sm:p-10"><Snowflake className="text-navy" size={30} /><h3 className="mt-5 text-2xl font-semibold">Kho điều hòa</h3><p className="mt-3 leading-7 text-slate">Môi trường ổn định hơn cho vật dụng nhạy cảm với nhiệt độ và độ ẩm.</p><dl className="comparison-list"><div><dt>Phù hợp</dt><dd>Tài liệu, đồ điện tử, đồ gỗ, hàng cần bảo quản</dd></div><div><dt>Môi trường</dt><dd>Được kiểm soát trong dải vận hành</dd></div><div><dt>Chi phí</dt><dd>Thường cao hơn kho tiêu chuẩn</dd></div></dl><ButtonLink to="/storage?type=climate&size=all&duration=3" variant="secondary">Xem kho điều hòa</ButtonLink></article></div></Container></section>

    <section className="section-space"><Container><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Chi phí rõ ràng</p><h2 className="mt-4 text-4xl font-bold tracking-tight">Biết mình sẽ trả cho điều gì trước khi xác nhận.</h2><p className="mt-5 leading-7 text-slate">WDP chưa công bố bảng giá thật trên website mẫu. Mỗi báo giá cần thể hiện riêng các khoản dưới đây, không gộp thành một con số mơ hồ.</p><ButtonLink className="mt-7" to="/storage">Chọn kho để yêu cầu báo giá</ButtonLink></div><div className="divide-y divide-border border-y border-border">{[[Warehouse,'Chi phí thuê','Tính theo loại kho, kích thước và thời gian thuê. Hiển thị sau khi WDP xác nhận tình trạng.'],[ReceiptText,'Tiền đặt cọc','Mức cọc và điều kiện hoàn cọc phải được ghi rõ trước khi ký hợp đồng.'],[PackageCheck,'Phí bổ sung','Khóa, kệ, pallet, vật tư đóng gói hoặc hỗ trợ vận chuyển chỉ tính khi khách chọn.']].map(([Icon,title,copy]) => { const I = Icon as typeof Warehouse; return <article key={String(title)} className="grid gap-4 py-6 sm:grid-cols-[40px_150px_1fr]"><I className="text-navy" /><h3 className="font-semibold">{String(title)}</h3><p className="text-sm leading-6 text-slate">{String(copy)}</p></article>})}</div></div></Container></section>

    <section id="amenities" className="section-space bg-white scroll-mt-24"><Container><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Vì sao chọn WDP</p><h2 className="mt-4 text-4xl font-bold tracking-tight">Một cơ sở được tổ chức cho việc lưu trữ thực tế.</h2><p className="mt-6 text-lg leading-8 text-slate">Từ lúc xe vào khu bốc dỡ đến khi khóa cửa kho, các tiện ích đều phục vụ việc chuyển và lấy đồ.</p></div><div className="grid gap-x-10 gap-y-8 sm:grid-cols-2">{[[ShieldCheck,'An ninh nhiều lớp','Camera khu vực chung, kiểm soát ra vào và khóa riêng.'],[ParkingCircle,'Dễ bốc dỡ','Khu đỗ xe và xe đẩy hỗ trợ việc chuyển đồ.'],[Box,'Đủ cỡ kho','Bốn nhóm sức chứa cho gia đình và kinh doanh.'],[CalendarDays,'Thuê linh hoạt','Chọn ngày bắt đầu và thời gian dự kiến trước khi hỏi kho.']].map(([Icon,title,copy]) => { const I = Icon as typeof ShieldCheck; return <article key={String(title)} className="border-t-2 border-navy pt-5"><I size={26} /><h3 className="mt-4 text-xl font-semibold">{String(title)}</h3><p className="mt-2 leading-6 text-slate">{String(copy)}</p></article>})}</div></div></Container></section>

    <section id="how-it-works" className="section-space bg-navy text-white scroll-mt-24"><Container><p className="eyebrow text-orange">Hành trình thuê kho</p><h2 className="mt-4 max-w-2xl text-4xl font-bold tracking-tight">Ba bước, mỗi bước một quyết định rõ ràng</h2><div className="mt-12 grid gap-10 md:grid-cols-3">{[['01','Tìm và xem chi tiết','Lọc theo kích thước, loại kho, ngày bắt đầu và thời gian thuê.'],['02','Gửi yêu cầu giữ chỗ','Cung cấp thông tin liên hệ. Chưa phát sinh thanh toán ở bước này.'],['03','WDP xác nhận','Nhận tình trạng kho, báo giá, tiền cọc và hướng dẫn hoàn tất thuê.']].map(([step,title,copy]) => <article key={step} className="border-t border-white/30 pt-6"><span className="text-sm font-bold text-orange">{step}</span><h3 className="mt-5 text-2xl font-semibold">{title}</h3><p className="mt-3 text-slate-300">{copy}</p></article>)}</div></Container></section>

    <section id="facility" className="section-space scroll-mt-24"><Container><div className="section-heading"><div><p className="eyebrow">Không gian tham khảo</p><h2>Rộng để di chuyển. Gọn để dễ quản lý.</h2></div><ButtonLink to="/storage" variant="secondary">Xem kho đang nhận yêu cầu <ChevronRight size={18} /></ButtonLink></div><div className="mt-12 grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><figure className="relative min-h-[500px] overflow-hidden"><img src={imageCredits.warehouse.src} alt="Ảnh minh họa một kho hàng rộng với thùng được sắp xếp trên kệ" className="absolute inset-0 h-full w-full object-cover" /><ImageCredit label={imageCredits.warehouse.label} href={imageCredits.warehouse.href} /></figure><div className="grid grid-cols-2 gap-4 lg:grid-cols-1"><figure className="relative min-h-60 overflow-hidden"><img src={imageCredits.aisle.src} alt="Ảnh minh họa lối đi trong kho" className="absolute inset-0 h-full w-full object-cover" /><ImageCredit label={imageCredits.aisle.label} href={imageCredits.aisle.href} /></figure><figure className="relative min-h-60 overflow-hidden"><img src={imageCredits.shelving.src} alt="Ảnh minh họa hệ thống kệ lưu trữ" className="absolute inset-0 h-full w-full object-cover" /><ImageCredit label={imageCredits.shelving.label} href={imageCredits.shelving.href} /></figure></div></div><p className="mt-4 text-xs text-slate">Các ảnh trên là ảnh stock được cấp phép, chỉ minh họa loại hình cơ sở. Hình ảnh WDP thực tế sẽ được thay thế khi có bộ ảnh chính thức.</p><div className="mt-8 grid gap-6 border-y border-border py-7 sm:grid-cols-2 lg:grid-cols-4"><p><Box /> 4 nhóm kích thước</p><p><KeyRound /> Quyền truy cập riêng</p><p><Camera /> Giám sát khu vực chung</p><p><ParkingCircle /> Khu bốc dỡ thuận tiện</p></div></Container></section>

    <section className="section-space bg-white"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Tiện ích bổ sung</p><h2 className="mt-4 text-4xl font-bold tracking-tight">Những thứ nhỏ giúp việc lưu kho dễ hơn.</h2><p className="mt-5 text-slate">Các lựa chọn này chỉ được tính phí khi khách yêu cầu và WDP xác nhận.</p></div><div className="grid gap-6 sm:grid-cols-2">{[[LockKeyhole,'Khóa kho','Khóa phù hợp với cửa kho riêng.'],[PackageCheck,'Vật tư đóng gói','Thùng carton, băng keo và màng bọc.'],[Box,'Kệ lưu trữ','Giúp phân loại và lấy đồ thuận tiện.'],[Warehouse,'Pallet','Kê hàng hóa khỏi mặt sàn khi cần.']].map(([Icon,title,copy]) => { const I = Icon as typeof Box; return <article key={String(title)} className="flex gap-4 border-b border-border pb-6"><I className="mt-1 shrink-0 text-navy" /><div><h3 className="font-semibold">{String(title)}</h3><p className="mt-1 text-sm text-slate">{String(copy)}</p></div></article>})}</div></div></Container></section>

    <section id="faq" className="section-space scroll-mt-24"><Container className="max-w-4xl"><div className="text-center"><p className="eyebrow">Câu hỏi thường gặp</p><h2 className="mt-4 text-4xl font-bold tracking-tight">Thông tin trước khi bạn gửi yêu cầu</h2></div><div className="mt-10 border-t border-border">{faqs.map(([question, answer]) => <details key={question} className="group border-b border-border"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-6 text-lg font-semibold focus-visible:outline-2 focus-visible:outline-navy">{question}<span className="text-navy transition group-open:rotate-90"><ChevronRight /></span></summary><p className="max-w-3xl pb-6 leading-7 text-slate">{answer}</p></details>)}</div></Container></section>

    <section className="bg-navy py-16 text-white"><Container className="flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow text-orange">Bắt đầu đúng kích thước</p><h2 className="mt-3 text-3xl font-bold">Chưa chắc đồ của bạn cần bao nhiêu chỗ?</h2><p className="mt-3 text-slate-200">So sánh bằng số thùng, nội thất và không gian phòng quen thuộc.</p></div><ButtonLink to="/size-guide" variant="light">Mở hướng dẫn kích thước <ArrowRight size={18} /></ButtonLink></Container></section>
  </>
}
