import { Body, Controller, Get, Headers, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common'; import { ApiBearerAuth, ApiBody, ApiConflictResponse, ApiCreatedResponse, ApiForbiddenResponse, ApiHeader, ApiNotFoundResponse, ApiOkResponse, ApiOperation, ApiParam, ApiQuery, ApiTags } from '@nestjs/swagger';
import { AssignSupportRequestDto, ResolveSupportRequestDto, UpdateSupportPriorityDto } from '../../openapi/api-dtos.js'; import { AuthGuard } from '../auth/auth.guard.js'; import type { AuthenticatedRequest } from '../auth/auth.types.js'; import { Roles, RolesGuard } from '../auth/roles.guard.js'; import { parseSupportQuery } from './support-query.js'; import { SupportService } from './support.service.js';
@Controller('manager/support-requests') @UseGuards(AuthGuard,RolesGuard) @Roles('MANAGER','ADMIN') @ApiTags('Manager Support') @ApiBearerAuth('bearerAuth')
export class ManagerSupportController {
 constructor(private readonly support:SupportService){}
 @Get() @ApiOperation({summary:'Danh sách Support Request cho Manager/Admin'}) @ApiQuery({name:'page',required:false}) @ApiQuery({name:'limit',required:false}) @ApiQuery({name:'status',required:false,enum:['OPEN','ASSIGNED','IN_PROGRESS','ESCALATED','RESOLVED']}) @ApiQuery({name:'category',required:false,enum:['UNIT_ISSUE','LOCK_OR_KEY_ISSUE','ACCESS_CODE_ISSUE','FACILITY_EQUIPMENT_FAILURE','PAYMENT_SUPPORT','STORED_ITEM_CONCERN','OTHER']}) @ApiQuery({name:'priority',required:false,enum:['LOW','MEDIUM','HIGH']}) @ApiQuery({name:'search',required:false}) @ApiOkResponse({description:'Customer/rental context và operational risk.'}) list(@Query() q:Record<string,unknown>){return this.support.listManager(parseSupportQuery(q))}
 @Get(':id') @ApiOperation({summary:'Chi tiết, maintenance state và future allocation context'}) @ApiParam({name:'id'}) @ApiNotFoundResponse({description:'Không tìm thấy.'}) get(@Param('id') id:string){return this.support.getManager(id)}
 @Patch(':id/assign') @ApiOperation({summary:'Assign/reassign STAFF'}) @ApiHeader({name:'Idempotency-Key',required:true}) @ApiBody({type:AssignSupportRequestDto}) @ApiCreatedResponse({description:'OPEN → ASSIGNED; các state chưa resolved có thể reassign.'}) @ApiForbiddenResponse({description:'CUSTOMER/STAFF bị chặn.'}) assign(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Headers('idempotency-key') key:string|undefined,@Body() body:Record<string,unknown>){return this.support.assign(id,body,key,req.user!)}
 @Patch(':id/priority') @ApiOperation({summary:'Đổi priority khi chưa RESOLVED'}) @ApiHeader({name:'Idempotency-Key',required:true}) @ApiBody({type:UpdateSupportPriorityDto}) priority(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Headers('idempotency-key') key:string|undefined,@Body() body:Record<string,unknown>){return this.support.priority(id,body,key,req.user!)}
 @Post(':id/resolve') @ApiOperation({summary:'Manager resolve case ESCALATED',description:'TRANSFER_RECOMMENDED chỉ ghi quyết định; không transfer hay mutate rental.'}) @ApiHeader({name:'Idempotency-Key',required:true}) @ApiBody({type:ResolveSupportRequestDto,examples:{transfer:{value:{resolutionType:'TRANSFER_RECOMMENDED',resolutionNote:'Customer relocation is recommended; no transfer performed.'}}}}) @ApiCreatedResponse({description:'ESCALATED → RESOLVED.'}) @ApiConflictResponse({description:'Không ở ESCALATED hoặc đã RESOLVED.'}) resolve(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Headers('idempotency-key') key:string|undefined,@Body() body:Record<string,unknown>){return this.support.resolveManager(id,body,key,req.user!)}
}
