import { Body, Controller, Get, Headers, Param, Post, Query, Req, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiBody, ApiConflictResponse, ApiCreatedResponse, ApiForbiddenResponse, ApiHeader, ApiNotFoundResponse, ApiOkResponse, ApiOperation, ApiParam, ApiQuery, ApiTags } from '@nestjs/swagger';
import { EscalateSupportRequestDto, ResolveSupportRequestDto } from '../../openapi/api-dtos.js'; import { AuthGuard } from '../auth/auth.guard.js'; import type { AuthenticatedRequest } from '../auth/auth.types.js'; import { Roles, RolesGuard } from '../auth/roles.guard.js'; import { parseSupportQuery } from './support-query.js'; import { SupportService } from './support.service.js';
@Controller('staff/support-requests') @UseGuards(AuthGuard, RolesGuard) @ApiTags('Staff Support') @ApiBearerAuth('bearerAuth')
export class StaffSupportController {
  constructor(private readonly support: SupportService) {}
  @Get() @Roles('STAFF', 'MANAGER', 'ADMIN') @ApiOperation({ summary: 'Danh sách Support Request vận hành' }) @ApiQuery({ name: 'page', required: false }) @ApiQuery({ name: 'limit', required: false }) @ApiQuery({ name: 'status', required: false, enum: ['OPEN','ASSIGNED','IN_PROGRESS','ESCALATED','RESOLVED'] }) @ApiQuery({ name: 'category', required: false, enum: ['UNIT_ISSUE','LOCK_OR_KEY_ISSUE','ACCESS_CODE_ISSUE','FACILITY_EQUIPMENT_FAILURE','PAYMENT_SUPPORT','STORED_ITEM_CONCERN','OTHER'] }) @ApiQuery({ name: 'priority', required: false, enum: ['LOW','MEDIUM','HIGH'] }) @ApiQuery({ name: 'assignedToMe', required: false, type: Boolean }) @ApiQuery({ name: 'search', required: false }) @ApiOkResponse({ description: 'Operational context, không có pricing history.' })
  list(@Req() req: AuthenticatedRequest, @Query() q: Record<string, unknown>) { return this.support.listStaff(parseSupportQuery(q), req.user!); }
  @Get(':id') @Roles('STAFF','MANAGER','ADMIN') @ApiOperation({ summary: 'Chi tiết Support Request cho vận hành' }) @ApiParam({ name: 'id' }) @ApiNotFoundResponse({ description: 'Không tìm thấy.' }) get(@Param('id') id: string) { return this.support.getStaff(id); }
  @Post(':id/start') @Roles('STAFF') @ApiOperation({ summary: 'Assigned Staff bắt đầu xử lý' }) @ApiHeader({ name: 'Idempotency-Key', required: true }) @ApiCreatedResponse({ description: 'ASSIGNED → IN_PROGRESS; rental/unit không đổi.' }) @ApiConflictResponse({ description: 'Sai state.' }) @ApiForbiddenResponse({ description: 'Không phải assigned Staff.' }) start(@Req() req: AuthenticatedRequest,@Param('id') id:string,@Headers('idempotency-key') key:string|undefined){return this.support.start(id,key,req.user!)}
  @Post(':id/resolve') @Roles('STAFF') @ApiOperation({ summary: 'Assigned Staff resolve vấn đề đơn giản' }) @ApiHeader({ name: 'Idempotency-Key', required: true }) @ApiBody({ type: ResolveSupportRequestDto, examples: { access: { value: { resolutionType:'ACCESS_RESTORED', resolutionNote:'Credential revalidated and tested.' } } } }) @ApiCreatedResponse({ description:'IN_PROGRESS → RESOLVED; không có financial side effect.' }) resolve(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Headers('idempotency-key') key:string|undefined,@Body() body:Record<string,unknown>){return this.support.resolveStaff(id,body,key,req.user!)}
  @Post(':id/escalate') @Roles('STAFF') @ApiOperation({ summary:'Escalate để Manager review' }) @ApiHeader({ name:'Idempotency-Key', required:true }) @ApiBody({ type:EscalateSupportRequestDto }) @ApiCreatedResponse({ description:'IN_PROGRESS → ESCALATED.' }) escalate(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Headers('idempotency-key') key:string|undefined,@Body() body:Record<string,unknown>){return this.support.escalate(id,body,key,req.user!)}
}
