import 'dotenv/config';
import { BadRequestException, ConflictException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { Prisma } from '../../generated/prisma/client.js';
import { PrismaService } from '../../prisma/prisma.service.js';
import type { PublicUser } from '../auth/auth.types.js';
import { SupportService } from './support.service.js';

const runId=randomUUID().slice(0,8), facilityId=`support-facility-${runId}`, typeId=`support-type-${runId}`;
const customerId=`support-customer-${runId}`, otherCustomerId=`support-other-${runId}`, staffId=`support-staff-${runId}`, otherStaffId=`support-staff2-${runId}`, managerId=`support-manager-${runId}`, adminId=`support-admin-${runId}`;
const actor=(id:string,role:PublicUser['role']):PublicUser=>({id,role,fullName:`${role} Support`,email:`${id}@example.test`,phone:''});
const customer=actor(customerId,'CUSTOMER'), otherCustomer=actor(otherCustomerId,'CUSTOMER'), staff=actor(staffId,'STAFF'), otherStaff=actor(otherStaffId,'STAFF'), manager=actor(managerId,'MANAGER');
const key=(name:string)=>`support-${name}-${randomUUID()}`;

describe('Support / Incident V1',()=>{
 let prisma:PrismaService,support:SupportService;
 beforeAll(async()=>{prisma=new PrismaService();await prisma.$connect();support=new SupportService(prisma);
  await prisma.facility.create({data:{id:facilityId,code:`SUP-${runId}`,name:'Support test',address:'Test'}});
  await prisma.storageType.create({data:{id:typeId,facilityId,code:`SUP-T-${runId}`,name:'Support type',sizeId:'small',sizeName:'Small',kicker:'Test',condition:'STANDARD',widthCm:100,lengthCm:100,heightCm:200,roomEquivalent:'Test',capacity:'Test',boxCount:'10',suitableItems:[],image:'https://example.test/a.jpg',imageAlt:'Test',floor:'Ground',access:'Test',features:[],monthlyRate:1000000}});
  await prisma.storageUnit.createMany({data:[0,1,2,3,4,5].map(i=>({storageTypeId:typeId,unitNumber:`SUP-${runId}-${i+1}`,floor:'Ground',zone:'S',row:1,position:i+1}))});
  await prisma.user.createMany({data:[{id:customerId,email:`${customerId}@x.test`,fullName:'Customer',role:'CUSTOMER',passwordHash:'secret-hash'},{id:otherCustomerId,email:`${otherCustomerId}@x.test`,fullName:'Other',role:'CUSTOMER',passwordHash:'secret-hash'},{id:staffId,email:`${staffId}@x.test`,fullName:'Staff',role:'STAFF',passwordHash:'secret-hash'},{id:otherStaffId,email:`${otherStaffId}@x.test`,fullName:'Other Staff',role:'STAFF',passwordHash:'secret-hash'},{id:managerId,email:`${managerId}@x.test`,fullName:'Manager',role:'MANAGER',passwordHash:'secret-hash'},{id:adminId,email:`${adminId}@x.test`,fullName:'Admin',role:'ADMIN',passwordHash:'secret-hash'}]});
 });
 async function cleanup(){await prisma.supportRequest.deleteMany({where:{reservation:{storageTypeId:typeId}}});await prisma.payment.deleteMany({where:{invoice:{reservation:{storageTypeId:typeId}}}});await prisma.invoice.deleteMany({where:{reservation:{storageTypeId:typeId}}});await prisma.rentalContract.deleteMany({where:{reservation:{storageTypeId:typeId}}});await prisma.reservationUnit.deleteMany({where:{reservation:{storageTypeId:typeId}}});await prisma.reservation.deleteMany({where:{storageTypeId:typeId}});await prisma.storageUnit.updateMany({where:{storageTypeId:typeId},data:{status:'AVAILABLE'}})}
 afterEach(cleanup);afterAll(async()=>{await cleanup();await prisma.storageUnit.deleteMany({where:{storageTypeId:typeId}});await prisma.storageType.delete({where:{id:typeId}});await prisma.user.deleteMany({where:{id:{in:[customerId,otherCustomerId,staffId,otherStaffId,managerId,adminId]}}});await prisma.facility.delete({where:{id:facilityId}});await prisma.$disconnect()});
 async function rental(owner=customerId,status:'ACTIVE'|'COMPLETED'='ACTIVE',unitIndex=0){const unit=(await prisma.storageUnit.findMany({where:{storageTypeId:typeId},orderBy:{unitNumber:'asc'}}))[unitIndex];const ref=`WDP-SUP-${randomUUID().slice(0,8)}`;const start=new Date(Date.now()-86400000*10),end=new Date(Date.now()+86400000*20);const quote={paymentPlan:'PAY_MONTHLY',depositAmount:1000000};const reservation=await prisma.reservation.create({data:{reservationCode:ref,customerId:owner,facilityId,storageTypeId:typeId,quantity:1,startDate:start,endDate:end,periodMode:'DURATION',durationMonths:1,availabilitySnapshot:{},quoteSnapshot:quote as Prisma.InputJsonValue,status:'CONFIRMED',confirmedAt:new Date(),idempotencyKey:key('reservation')}});const allocation=await prisma.reservationUnit.create({data:{reservationId:reservation.id,storageUnitId:unit.id,plannedStartDate:start,plannedEndDate:end,...(status==='COMPLETED'?{releasedAt:new Date(),actualVacatedAt:new Date()}: {})}});const contract=await prisma.rentalContract.create({data:{contractCode:`${ref}-C01`,reservationId:reservation.id,reservationUnitId:allocation.id,status,startDate:start,endDate:end,...(status==='ACTIVE'?{activatedAt:start}:{completedAt:new Date()})}});await prisma.storageUnit.update({where:{id:unit.id},data:{status:status==='ACTIVE'?'OCCUPIED':'AVAILABLE'}});const invoice=await prisma.invoice.create({data:{invoiceCode:`${ref}-I01`,reservationId:reservation.id,type:'INITIAL',billingCycle:1,status:'OPEN',rentalAmount:1000000n,depositAmount:1000000n,totalAmount:2000000n,amountPaid:0n,balanceDue:2000000n}});return{reservation,allocation,contract,unit,invoice,quote}}
 const create=(r:any,category:string,actorUser=customer,extra:Record<string,unknown>={},requestKey=key('create'))=>support.createCustomer(actorUser,{reservationId:r.reservation.id,rentalContractId:r.contract.id,storageUnitId:r.unit.id,category,subject:`${category} subject`,description:'Safe operational description without credentials.',...extra},requestKey);

 it('creates every operational category only for own ACTIVE OCCUPIED rental and allows multiple requests',async()=>{const r=await rental();for(const c of ['UNIT_ISSUE','LOCK_OR_KEY_ISSUE','ACCESS_CODE_ISSUE','FACILITY_EQUIPMENT_FAILURE','STORED_ITEM_CONCERN'])expect(await create(r,c)).toMatchObject({category:c,status:'OPEN',priority:'MEDIUM',unit:{status:'OCCUPIED'}});expect(await prisma.supportRequest.count({where:{reservationId:r.reservation.id}})).toBe(5);await expect(create(r,'UNIT_ISSUE',otherCustomer)).rejects.toBeInstanceOf(NotFoundException);const done=await rental(customerId,'COMPLETED',1);await expect(create(done,'UNIT_ISSUE')).rejects.toMatchObject({response:{code:'ACTIVE_RENTAL_REQUIRED'}})},60000);
 it('supports owned PAYMENT_SUPPORT without mutating invoice and rejects foreign invoice',async()=>{const r=await rental();const before=await prisma.invoice.findUniqueOrThrow({where:{id:r.invoice.id}});const request=await support.createCustomer(customer,{reservationId:r.reservation.id,invoiceId:r.invoice.id,category:'PAYMENT_SUPPORT',subject:'Invoice question',description:'Please explain this invoice.'},key('payment'));await support.assign(request.id,{staffUserId:staffId},key('assign'),manager);await support.start(request.id,key('start'),staff);await support.resolveStaff(request.id,{resolutionType:'PAYMENT_GUIDANCE',resolutionNote:'Invoice state explained.'},key('resolve'),staff);expect(await prisma.invoice.findUniqueOrThrow({where:{id:r.invoice.id}})).toEqual(before);const foreign=await rental(otherCustomerId,'ACTIVE',1);await expect(support.createCustomer(customer,{reservationId:r.reservation.id,invoiceId:foreign.invoice.id,category:'PAYMENT_SUPPORT',subject:'Wrong invoice',description:'Should be rejected.'},key('foreign-invoice'))).rejects.toBeInstanceOf(BadRequestException)},60000);
 it('is create-idempotent and enforces customer ownership/read privacy',async()=>{const r=await rental();const k=key('same');const first=await create(r,'ACCESS_CODE_ISSUE',customer,{},k),retry=await create(r,'ACCESS_CODE_ISSUE',customer,{},k);expect(retry.id).toBe(first.id);expect((await support.listCustomer(customerId,{page:1,limit:20})).total).toBe(1);expect((await support.listCustomer(otherCustomerId,{page:1,limit:20})).total).toBe(0);await expect(support.getCustomer(otherCustomerId,first.id)).rejects.toBeInstanceOf(NotFoundException);expect(JSON.stringify(await support.getCustomer(customerId,first.id))).not.toContain('secret-hash')});
 it('enforces assignment/priority/start roles and keeps unit OCCUPIED',async()=>{const r=await rental(),request=await create(r,'UNIT_ISSUE');await expect(support.assign(request.id,{staffUserId:customerId},key('bad'),manager)).rejects.toBeInstanceOf(BadRequestException);await expect(support.assign(request.id,{staffUserId:staffId},key('self'),staff)).rejects.toBeInstanceOf(ForbiddenException);expect(await support.assign(request.id,{staffUserId:staffId},key('assign'),manager)).toMatchObject({status:'ASSIGNED'});await expect(support.priority(request.id,{priority:'HIGH'},key('staff-priority'),staff)).rejects.toBeInstanceOf(ForbiddenException);expect(await support.priority(request.id,{priority:'HIGH'},key('priority'),manager)).toMatchObject({priority:'HIGH'});await expect(support.start(request.id,key('wrong'),otherStaff)).rejects.toBeInstanceOf(ForbiddenException);expect(await support.start(request.id,key('start'),staff)).toMatchObject({status:'IN_PROGRESS'});expect((await prisma.storageUnit.findUniqueOrThrow({where:{id:r.unit.id}})).status).toBe('OCCUPIED')},60000);
 it('lets assigned Staff resolve simple access issue with no financial/maintenance side effects',async()=>{const r=await rental(),request=await create(r,'ACCESS_CODE_ISSUE');const quote=(await prisma.reservation.findUniqueOrThrow({where:{id:r.reservation.id}})).quoteSnapshot;await support.assign(request.id,{staffUserId:staffId},key('assign'),manager);await support.start(request.id,key('start'),staff);const resolved=await support.resolveStaff(request.id,{resolutionType:'ACCESS_RESTORED',resolutionNote:'Credential revalidated without storing the secret.'},key('resolve'),staff);expect(resolved).toMatchObject({status:'RESOLVED',resolutionType:'ACCESS_RESTORED',unit:{status:'OCCUPIED'}});expect(await prisma.maintenanceRequest.count({where:{storageUnitId:r.unit.id}})).toBe(0);expect((await prisma.reservation.findUniqueOrThrow({where:{id:r.reservation.id}})).quoteSnapshot).toEqual(quote);expect(await prisma.payment.count({where:{invoiceId:r.invoice.id}})).toBe(0);await expect(support.priority(request.id,{priority:'LOW'},key('late'),manager)).rejects.toBeInstanceOf(ConflictException)},60000);
 it('escalates with reason and Manager records TRANSFER_RECOMMENDED without performing transfer',async()=>{const r=await rental(),request=await create(r,'FACILITY_EQUIPMENT_FAILURE');const future=await rental(otherCustomerId,'ACTIVE',1);const futureAllocation=await prisma.reservationUnit.create({data:{reservationId:future.reservation.id,storageUnitId:r.unit.id,plannedStartDate:new Date(Date.now()+86400000*30),plannedEndDate:new Date(Date.now()+86400000*60)}});await support.assign(request.id,{staffUserId:staffId},key('assign'),manager);await support.start(request.id,key('start'),staff);expect(()=>support.escalate(request.id,{reason:''},key('empty'),staff)).toThrow(BadRequestException);expect(await support.escalate(request.id,{reason:'Unit cannot remain safe; Manager review required.'},key('escalate'),staff)).toMatchObject({status:'ESCALATED'});const resolved=await support.resolveManager(request.id,{resolutionType:'TRANSFER_RECOMMENDED',resolutionNote:'Relocation recommended; no transfer performed.'},key('manager-resolve'),manager);expect(resolved).toMatchObject({status:'RESOLVED',resolutionType:'TRANSFER_RECOMMENDED',unit:{status:'OCCUPIED'}});expect(await prisma.maintenanceRequest.count({where:{storageUnitId:r.unit.id}})).toBe(0);expect(await prisma.rentalContract.findUniqueOrThrow({where:{id:r.contract.id}})).toMatchObject({status:'ACTIVE',reservationUnitId:r.allocation.id});expect(await prisma.reservationUnit.findUniqueOrThrow({where:{id:r.allocation.id}})).toMatchObject({releasedAt:null,storageUnitId:r.unit.id});expect(await prisma.reservationUnit.findUniqueOrThrow({where:{id:futureAllocation.id}})).toMatchObject({releasedAt:null,storageUnitId:r.unit.id})},60000);
 it('makes concurrent start and resolve-vs-escalate races safe',async()=>{const r=await rental(),request=await create(r,'UNIT_ISSUE');await support.assign(request.id,{staffUserId:staffId},key('assign'),manager);const starts=await Promise.allSettled([support.start(request.id,key('start1'),staff),support.start(request.id,key('start2'),staff)]);expect(starts.filter(x=>x.status==='fulfilled')).toHaveLength(1);const race=await Promise.allSettled([support.resolveStaff(request.id,{resolutionType:'ON_SITE_RESOLVED',resolutionNote:'Resolved on site.'},key('resolve'),staff),support.escalate(request.id,{reason:'Manager review required.'},key('escalate'),staff)]);expect(race.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(['RESOLVED','ESCALATED']).toContain((await prisma.supportRequest.findUniqueOrThrow({where:{id:request.id}})).status)},60000);
});
